wip

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -29,8 +29,7 @@ jobs:
       # Allows creating a release
       contents: write
     outputs:
-      release-id: ${{ steps.create-github-release.outputs.release-id }}
-      release-auto-tag: ${{ steps.create-github-release.outputs.release-auto-tag }}
+      auto-tag: ${{ steps.create-github-release.outputs.auto-tag }}
     steps:
       - name: Download artifacts
         uses: actions/download-artifact@v3
@@ -45,7 +44,7 @@ jobs:
           build_id="${{ github.run_id }}-${{ github.run_attempt }}"
           auto_tag="auto-${build_id}"
 
-          echo "release-auto-tag=${auto_tag}" >> "${GITHUB_OUTPUT}"
+          echo "auto-tag=${auto_tag}" >> "${GITHUB_OUTPUT}"
 
           repo="${{ github.repository }}"
           repo_owner="${repo%%/*}"
@@ -58,7 +57,7 @@ jobs:
 
           echo "release-id=${release_id}" >> "${GITHUB_OUTPUT}"
           echo "release-url=${release_url}" >> "${GITHUB_OUTPUT}"
-          echo "::notice title=Update Release::Please review and finish editing the release draft."
+          echo "::notice title=GitHub Release::Please review and finish editing the release draft."
   publish-github-release:
     needs: create-github-release
     runs-on: ubuntu-latest
@@ -74,22 +73,17 @@ jobs:
           GH_TOKEN: ${{ secrets.github_token }}
         run: |
           gh config set prompt disabled || exit 1
-          release_id="${{ needs.create-github-release.outputs.release-id }}"
-          if [[ -z "${release_id}" ]]; then
-            echo "::error title=Update Release::Release ID is missing."
-            exit 1
-          fi
-          auto_tag="${{ needs.create-github-release.outputs.release-auto-tag }}"
+          auto_tag="${{ needs.create-github-release.outputs.auto-tag }}"
           if [[ -z "${auto_tag}" ]]; then
-            echo "::error title=Update Release::Auto tag is missing."
+            echo "::error title=GitHub Release::Auto tag is missing."
             exit 1
           fi
-          tag=$(gh api graphql -f query="query { repository(owner: \"${repo_owner}\", name: \"${repo_name}\") { release(id: \"${release_id}\") { tagName } } }" -q ".data.repository.release.tagName") || exit 1
-          if [[ "${tag}" == "${auto_tag}" ]]; then
-            echo "::error title=Update Release::Did you forget to update the tag of the release?"
+          output=$(gh api graphql -f query="query { repository(owner: \"${repo_owner}\", name: \"${repo_name}\") { release(tagName: \"${auto_tag}\") { id } } }" -q '.data.repository.release.id') || exit 1
+          if [[ ! -z "${output}" ]]; then
+            echo "::error title=GitHub Release::Did you forget to update the tag of the release?"
             exit 1
           fi
           if ! gh release --repo "${{ github.repository }}" edit --verify-tag; then
-            echo "::error title=Update Release::Please make sure to push the tag for the release."
+            echo "::error title=GitHub Release::Please make sure to push the tag for the release."
             exit 1
           fi
